### ISSUE TITLE
Agregar usuarios a NodeSchool chapter-organizers

### ISSUE THREAD

**Issue by D3Portillo** [nodeschool/sanmiguel#6]
Issue para listar las solicitudes de union al repo de organizadores de captitulos de NodeSchool San Miguel :+1: :tada: :taco: :taco: :100: :fire: :fire:

**Comment by D3Portillo** [comment]
@nodeschoolbot add-user arnoldou

**Comment by riyadhalnur** [comment]
I have added @arnoldou to the `chapter-organizers` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-team-user sanmiguel arnoldou

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @arnoldou to the `sanmiguel` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-team-user sanmiguel arnoldou

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @arnoldou to the `sanmiguel` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-user moudev

**Comment by riyadhalnur** [comment]
I have added @moudev to the `chapter-organizers` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-team-user sanmiguel moudev

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @moudev to the `sanmiguel` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-team-user sanmiguel moudev

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @moudev to the `sanmiguel` team.

**Comment by arnoldou** [comment]
?

**Comment by D3Portillo** [comment]
acepte el correo o revise la pagina inicial de github, porfa

**Comment by arnoldou** [comment]
replicando..



Arnoldo Umaña
2669-3000
7877-2146
 

    En jueves, 14 de junio de 2018 11:38:51 GMT-6, Denny Portillo <notifications@github.com> escribió:  
 
 
acepte el correo o revise la pagina inicial de github, porfa

**Comment by D3Portillo** [comment]
@nodeschoolbot add-team-user sanmiguel Mario191217

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @Mario191217 to the `sanmiguel` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-user sanmiguel Mario191217

**Comment by riyadhalnur** [comment]
I have added @sanmiguel to the `chapter-organizers` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-team-user sanmiguel Mario191217

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by D3Portillo** [comment]
@nodeschoolbot add-team-user sanmiguel Mario191217

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @Mario191217 to the `sanmiguel` team.

**Comment by riyadhalnur** [comment]
I have encountered an error doing this :(

```
Error: connect ETIMEDOUT 192.30.255.117:443
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1207:14)
```

**Comment by D3Portillo** [comment]
@nodeschoolbot add-user  Mario191217

**Comment by riyadhalnur** [comment]
I have added @Mario191217 to the `chapter-organizers` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-team-user sanmiguel Mario191217

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @Mario191217 to the `sanmiguel` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-team-user sanmiguel Nadelina

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @Nadelina to the `sanmiguel` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-team-user sanmiguel soldierhd

**Comment by riyadhalnur** [comment]
I cannot find the team `sanmiguel`

**Comment by riyadhalnur** [comment]
I have invited @soldierhd to the `sanmiguel` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-user soldierhd

**Comment by riyadhalnur** [comment]
I have added @soldierhd to the `chapter-organizers` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-user Nadelina

**Comment by riyadhalnur** [comment]
I have added @Nadelina to the `chapter-organizers` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-user Nes70rMend024

**Comment by riyadhalnur** [comment]
I have added @Nes70rMend024 to the `chapter-organizers` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-user X905

**Comment by riyadhalnur** [comment]
I have added @X905 to the `chapter-organizers` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-user AleeAR

**Comment by riyadhalnur** [comment]
I have added @AleeAR to the `chapter-organizers` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-user Monge1h

**Comment by riyadhalnur** [comment]
I have added @Monge1h to the `chapter-organizers` team.

**Comment by D3Portillo** [comment]
@nodechoolbot add-user Nadelina

**Comment by D3Portillo** [comment]
@nodeschoolbot add-user Nadelina

**Comment by riyadhalnur** [comment]
I have added @Nadelina to the `chapter-organizers` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-user chrisft25

**Comment by riyadhalnur** [comment]
I have added @chrisft25 to the `chapter-organizers` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-user chrisft25

**Comment by riyadhalnur** [comment]
I have added @chrisft25 to the `chapter-organizers` team.

**Comment by D3Portillo** [comment]
@nodeschoolbot add-user erjosara8916

**Comment by riyadhalnur** [comment]
I have added @erjosara8916 to the `chapter-organizers` team.
